version: "3"
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4510-4559:4510-4559'
      - '4566:4566'
    environment:
      - DEFAULT_REGION=sa-east-1
    volumes: 
      - ./init-scripts:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock

    