version: "3"
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4597:4566-4597'
    environment:
      - DEFAULT_REGION=sa-east-1
  aws_cli:
    image: amazon/aws-cli
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 10

        # Create profile
        aws configure set region sa-east-1 --profile=localstack
        aws configure set aws_access_key_id default_access_key --profile=localstack
        aws configure set aws_secret_access_key default_secret_key --profile=localstack

        # Optional commands to check created configurations
        aws configure list-profiles
        aws configure list
        cat /root/.aws/config
        cat /root/.aws/credentials

        ## RESOURCE CREATION AND STARTUP ## (can have multiple commands)

        # Creating SQS
        aws sqs create-queue --endpoint-url=http://localstack:4566 --queue-name=local_queue_my --profile=localstack
        aws sqs create-queue --endpoint-url=http://localstack:4566 --queue-name=local_queue_my_1 --profile=localstack
       # aws sqs list-queues --endpoint-url=http://localhost:4566 - to list created sqs

      "