version: "3"
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566-4597:4566-4597'
    environment:
      - DEFAULT_REGION=sa-east-1
  aws_cli:
    image: amazon/aws-cli
    depends_on: 
      - localstack
    entrypoint: /bin/sh -c
    command: >  
     '
     COUNTER=15;
     SQS_DESIRED_STATE="sqs running";
     SERVICE_ACTUAL_STATE=0;
     
      while [ $$COUNTER -ne 0 ] && [ $$SERVICE_ACTUAL_STATE != 1 ]
      
      do 
      RESPONSE=$$(curl -sb --connect-timeout 2 /dev/null "localstack:4566/health?redirect" | tr -cd [^[:alnum:][:space:]]+) 
      echo " Responce from Localstack $$RESPONSE"; 

      if [[ $$RESPONSE == *"$$SQS_DESIRED_STATE"* ]]; then SERVICE_ACTUAL_STATE=1; else SERVICE_ACTUAL_STATE=0; fi;
      
      COUNTER=$$((COUNTER-1)); 
      echo "Service is not ready yet! $$COUNTER retries left."; 
      sleep 3; 
      done; 
      echo backend is up;

      echo "########### Creating profile ###########"

      aws configure set aws_access_key_id default_access_key --profile=localstack
      aws configure set aws_secret_access_key default_secret_key --profile=localstack
      aws configure set region sa-east-1 --profile=localstack

      echo "########### Listing profile ###########"
      aws configure list --profile=localstack

      echo "########### Creating SQS ###########"
      aws sqs create-queue --endpoint-url=http://localstack:4566 --queue-name=local_queue_my --profile=localstack
      aws sqs create-queue --endpoint-url=http://localstack:4566 --queue-name=local_queue_my_1 --profile=localstack

      echo "########### Listing SQS ###########"
      aws sqs list-queues --endpoint-url=http://localstack:4566 --profile=localstack

      '

